apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: | 
    - rolearn: arn:aws:iam::030240492505:role/udacityclouddevopscapstone-EKSRole-RPVHC94FLYC2
      username: system:node:{{EC2PrivateDNSName}} 
      groups: 
        - system:bootstrappers 
        - system:nodes 
  mapUsers: | 
    - userarn: arn:aws:iam::030240492505:user/devin
      username: designated_user 
      groups: 
        - system:masters